-- this is for text labels and other things/written by hashtag i might be wrong since im not copypasting it from studio and this is all by muscle memory 😫😫

local txt = script.Parent

local time = tick()
local r = tick(math.sin(2+1) * 0.5 + 0.5)
local g = tick(math.sin(2+2) * 0.5 + 0.5)
local b = tick(math.sin(2+4) * 0.5 + 0.5)

txt.TextColor = Color3.new(r,g,b) -- its format without rainbow would be usually (255,255,255) 
end
